# This Dockerfile builds the API only.

FROM python:3.8
WORKDIR /app

COPY api ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", "0.0.0.0:5000", "app:app"]