version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: course-management-hub-api
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: course-management-hub-client
    ports:
      - "3000:80"

  # mongodb:
  #   image: mongo
  #   container_name: mongo
  #   restart: unless-stopped
  #   command: mongod --auth
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: "admin"
  #     MONGO_INITDB_ROOT_PASSWORD: "password"
  #     MONGO_INITDB_DATABASE: webapp
  #     MONGODB_DATA_DIR: /data/db
  #   volumes:
  #     - mongodbdata:/data/db