version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: course-management-hub-api
    ports:
      - "5000:5000"
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: course-management-hub-client
    ports:
      - "3000:80"
